export const etcEvents = [
  {
    id: 41,
    eventName: "The Ancient Ruins",
    department: "ECOMP Department",
    categories: ["ETC"],
    type: "Inter",
    team: true,
    location: "Offline (EComp Floor Lab 6)",
    date: "29th OCT",
    time: "10 AM",
    event_coordinators: [
      {
        name: "Pritam Biswas",
        phone: "7387665601",
      },
      {
        name: "Tanisha S.S Kantak",
        phone: "8999189053",
      },
    ],
    rules: {
      Rules: [
    "Entry fee per team is ₹150/-",
        "A team can comprise of max 3 members.",
        "The online registration should be done prior to the event. The registration will be on first come first serve basis as limited number of seats are available.",
    "The teams must be present on the given time. Any further delay can hinder their participation.",
    "A set of tasks will be assigned by the coordinators to the participants on the day of the event itself. Each task will have a time limit.",
    "Participants must finish the task within the given time limit.",
    "Required instructions for the tasks and about the time limit shall be told 1 hour prior to the event.",
    "It is the team's responsibility to listen to the rules properly given by the coordinators. Teams can ask for any doubt or questions related to rules of this event before entering and once entered i.e once the timer starts player should play in a fair manner and no restart or asking for stuff to coordinators will be allowed",
    "Any form or cheating, damage to property or props, violence etc won't be tolerated and can lead to immediate disqualification.",
    "Final decision shall be made by the coordinators.",
    "Violation of any rules can lead to disqualification.",
    "The team that manages to finish the tasks and escape the room in the shortest duration of time shall be claimed as winners."
      ],
  FAQs: [
    "1. What will the tasks be like?", " Ans - The tasks will comprise of 1 coding task, 1 technical task and few other mind boggling puzzles.",
    "2. Is there a registration fee?", "Ans - Yes. Entry fee per team is ₹150. Payment details are given in the Registeration form.",
    "Decision taken by Co-Ordinators will be final in case any discrepancies!"
  ],
    },
    prize: [5000],
    form: "https://forms.gle/QzVzipifwZRzaUp1A",
    poster: "https://raw.githubusercontent.com/TECHYON2022/techyonAssets/main/ETC/posters/Escape Room.png",
    rulebook: "../rulebook/COMP/decrypt.pdf",
    image: "https://raw.githubusercontent.com/TECHYON2022/techyonAssets/main/ETC/thumbnail/Escape%20Room.png",
  },
  {
    id: 42,
    eventName: "Line Follower",
    department: "ECOMP Department",
    categories: ["ETC"],
    type: "Inter",
    team: true,
    location: "Offline (L11 & L12)",
    date: "28th OCT",
    time: "10 AM",
    event_coordinators: [
      {
        name: "Shubham Bhalerao",
        phone: "8329688423",
      },
      {
        name: "Sufiyan Munshi",
        phone: "8668604717",
      },
    ],
    rules: {
      Rules: [
        "A team can comprise of a maximum of 4 members.",
    "The competition will be of 2 rounds. Round 1 shall be a qualifier round and round 2 shall be the final round.",
    "In round 1, each team will give 2 time-trials. Least time and with best out of 2 given trails will be judged upon.",
    "For the 1st trial a test run of 3 Mins will be given after which, immediately 1st time trial will follow", 
    "Team can give 2nd and Final trail immediately after 1st or later in the competition. There won’t be any TEST RUN for 2nd trial.", 
    "The bot must cover the entire track within 4 min minutes to qualify for the final round", 
    "Any shortcut paths and deviation from the main line will lead to placing of the bot back to the nearest check point. Coordinators decision will be counted as the final.", 
    "In case if no bot is able to complete the track in given time, the bot covering maximum checkpoint in minimum time will be shortlisted for the final round.", 
    "Width of the line will be 3cm.The participants shall be informed in prior by the event coordinators if there is any change in the width of the line.",
    "The Line Follower Bot must be fully self-contained and must not be externally operated by wire or remote radio control during the course of the race.",
    "Before commencement of the actual racing, the teams will be allowed to test their bots on the track but only for limited period of time as decided by the coordinators.",
    "Once the bot is placed on the track, a maximum of 8 touches will be allowed to reset the bot on the right track and a penalty of 5 sec per touch shall be added to the total time.",
    "Winner shall be the group which finishes the track in the shortest time. In case no team manages to finish the track, then the prize shall be given to the team who completes most part of the track in shortest time and with minimum touches.",
      ],
      "Bot specifications": [
        "The overall specifications of the bot must not exceed the following (including tolerance):",
        "28 cm in length, 22 cm in width, 5 kg in total weight, and 20 cm in overall height.",
        "No Lego and ready-made bot.",
        "Max voltage 12V",
      ],
      FAQs: [
        "1. Is there a registration fee?  Yes. Entry fee per team is ₹150. Payment details are given in the Registeration form.",
        "Decision taken by Co-Ordinators will be final in case any discrepancies!",
      ],
    },
    prize: [6000, 2000],
    form: "https://forms.gle/YvHjw9u8ysEFC8wW8",
    poster: "https://raw.githubusercontent.com/TECHYON2022/techyonAssets/main/ETC/posters/Line Follower.png",
    rulebook: "../rulebook/COMP/decrypt.pdf",
    image: "https://raw.githubusercontent.com/TECHYON2022/techyonAssets/main/ETC/thumbnail/Line%20Follower.png",
  },
  {
    id: 43,
    eventName: "Pitch Tank",
    department: "ECOMP Department",
    categories: ["ETC"],
    type: "Inter",
    team: true,
    location: "Offline (EComp Floor Lab 7)",
    date: "27th OCT",
    time: "10 AM",
    event_coordinators: [
      {
        name: "Abhijeet Singh",
        phone: "9421098900",
      },
      {
        name: "Keegan Barreto",
        phone: "8208078519",
      },
    ],
    rules: {
      Rules: [
        "Teams can comprise of maximum 4 members.",
        "Pitch should solve a real problem.",
        "Teams should fill in the details about their pitch, including presentations, in the registration form.",
        "Teams will have 5 minutes to present their ideas to the judges and will have questions from judges for next 5 minutes.",
        "The decision of judges will be final.",
        "Serious conflicts will lead to disqualification.",
    ],
  FAQs: [
        "1. Is there a registration fee?  Ans - No registration fee",
        "Decision taken by Co-Ordinators will be final in case any discrepancies!",
      ],
    },
    prize: [4000, 2000],
    form: "https://forms.gle/Ut1FU93B735MqL5i9",
    poster: "https://raw.githubusercontent.com/TECHYON2022/techyonAssets/main/ETC/posters/Pitch Tank.png",
    rulebook: "../rulebook/COMP/decrypt.pdf",
    image: "https://raw.githubusercontent.com/TECHYON2022/techyonAssets/main/ETC/thumbnail/Pitch%20Tank.png",
  },
  {
    id: 44,
    eventName: "Electronic Art",
    department: "ECOMP Department",
    categories: ["ETC"],
    type: "Intra",
    team: true,
    location: "Offline (EComp Floor Lab 3 & Lab 4)",
    date: "27th OCT",
    time: "10 AM",
    event_coordinators: [
      {
        name: "Anushri Redkar",
        phone: "7767024998",
      },
      {
        name: "Ritika Naik",
        phone: "9881500659",
      },
    ],
    rules: {
      Rules: [
    "Each team can have a maximum of 3 members.",
        "Theme for this event is: CREEP IT REAL : PUT A SPELL IN YOUR ART AND CREEP EVRYONE OUT (Halloween theme)",
        "Under This theme participants are required to make a small miniature representation or diorama of any haunted scenes or Halloween based model.",
        "The size of the artwork cannot exceed more then 50*50*50 cm",
        "Use of all electronic components is allowed such as different leds ,led panels, sensors and all those components which will bring the spark in the artwork.",
        "Use of microcontrollers is also allowed.",
        "Participants should be present at the designated class/lab prior the event timing, failing to will lead to disqualification.",
      ],
      FAQs: [
        "1. Who can participate?  Ans - Any student from Padre Conceicao College of Engineering irrespective of their department can participate. ",
        "2. Is there a registration fee?  Ans - No registration fee",
        "Decision taken by Co-Ordinators will be final in case any discrepancies!",
      ],
    },
    prize: [3000, 2000],
    form: "https://forms.gle/ZmroJbkE4a5BYbaq8",
    poster: "https://raw.githubusercontent.com/TECHYON2022/techyonAssets/main/ETC/posters/Electronic Art.png",
    rulebook: "../rulebook/COMP/decrypt.pdf",
    image: "https://raw.githubusercontent.com/TECHYON2022/techyonAssets/main/ETC/thumbnail/EA.png",
  },
  {
    id: 45,
    eventName: "Design With Canva",
    department: "ECOMP Department",
    categories: ["ETC"],
    type: "Intra",
    team: false,
    location: "Offline (EComp Floor Lab 1 & 2)",
    date: "28th OCT",
    time: "10 AM",
    event_coordinators: [
      {
        name: "Melroy Pereira",
        phone: "7875295856",
      },
      {
        name: "Shaikh Inamul",
        phone: "8600965149",
      },
    ],
    rules: {
      Rules: [
        "Participants are allowed to use free Templates with enough changes to make it look original.",
        "Only free version of canva is allowed",
        "Accounts will be given.",
        "Use of mobile phones during the entire period of contest is prohibited.",
        "Participants cannot cheat or copy from other participants. Doing so will result in disqualification.",
        "Topics will be given on the spot.",
        "Participants should stick to the topic given to them.",
        "The Time limit is 2 hrs. Participants must finish the assigned task within the time limit. No extra time will be given.",
        "Participants must adhere by the rules and co-operate with the coordinators.",
      ],
      FAQs: [
        "1. Is there a registration fee?  Ans - No registration fee",
        "Decision taken by Co-Ordinators will be final in case any discrepancies!",
      ],
    },
    prize: [3000, 2000, 1000],
    form: "https://forms.gle/hheJfnLh8a2MRnoKA",
    poster: "https://raw.githubusercontent.com/TECHYON2022/techyonAssets/main/ETC/posters/Design with Canva.png",
    rulebook: "../rulebook/COMP/decrypt.pdf",
    image: "https://raw.githubusercontent.com/TECHYON2022/techyonAssets/main/ETC/thumbnail/Canva.png",
  },
  {
    id: 46,
    eventName: "Call of Duty: Mobile BR Tornament",
    department: "ECOMP Department",
    categories: ["ETC"],
    type: "Intra",
    team: true,
    location: "Offline (EComp Floor L11 & L12)",
    date: "29th OCT",
    time: "11 AM",
    event_coordinators: [
      {
        name: "SHAIKH INAMUL",
        phone: "8600965149",
      },
      {
        name: "SARVESH LAD",
        phone: "9518745617",
      },
    ],
    rules: {
      Rules: [
        "25 teams in a lobby.",
        "Each team should consist of 4 players.",
        "All Teams and all players must present at the event 20 mins before the event time.",
        "Room code will be shared 15 mins before the event.",
        "Players should have all the Battle Royal Maps downloaded beforehand.",
        "Cheating or Hacking will not be tolerated and will result in disqualification of the entire team.",
        "Ranking will be decided based on point system.",
        "Use of foul language or other foul actions will result in disqualification of the team.",
        "Emulators not allowed. Players can either play on iOS devices or Android devices",
      ],
  "Point System and Table":  [
    "There will be two rounds where all the 25 squads will fight for the top spot.",
    "#1 spot - +15 points",
    "#2 spot - +10 points",
    "#3 spot - +7 points",
    "#4 spot - +6 points",
    "#5 spot - +5 points",
    "#6 spot - +4 points",
    "#7 spot - +3 points",
    "#8 spot - +2 points",
    "#9 spot - +1 point",
    "Other placements spots - 0 points.",
  ],
      FAQs: [
        "1. Is there a registration fee?  Ans - Yes. Entry fee per team is ₹200. Payment details are given in the Registeration form.",
        "3. What should you have?  Ans - A PC/Laptop with internet access and preferably Google Chrome browser installed.",
        "Decision taken by Co-Ordinators will be final in case any discrepancies!",
      ],
    },
    prize: [4000],
    form: "https://forms.gle/tNNX2yb3JS9tijsf6",
    poster: "https://raw.githubusercontent.com/TECHYON2022/techyonAssets/main/ETC/posters/CoD Mobile.png",
    rulebook: "../rulebook/COMP/decrypt.pdf",
    image: "https://raw.githubusercontent.com/TECHYON2022/techyonAssets/main/ETC/thumbnail/CoD.png",
  },
  {
    id: 47,
    eventName: "VFX",
    department: "ECOMP Department",
    categories: ["ETC"],
    type: "Intra",
    team: false,
    location: "Offline (EComp Floor Lab 7)",
    date: "28th OCT",
    time: "2 PM",
    event_coordinators: [
      {
        name: "Sharv Shripad Shetye",
        phone: "9503577482",
      },
    ],
    rules: {
      Details: [
        "1. Participation Fees: 100rs per person",
        "2. Registrations allowed up untill 26th October",
        "3. Basic Knowledge not required for this workshop as everything will be taught from scratch.",
        "4. It will be a one on one session with the Students.",
    "5. Certificate to be provided at the end of the workshop (physical as well as E-Certificate)",
    "6. Free snacks and beverages will be provided to everyone.",
      ],
    },
    prize: [],
    form: "https://forms.gle/jgygju5aETjZEr6L6",
    poster: "https://raw.githubusercontent.com/TECHYON2022/techyonAssets/main/ETC/posters/VFX Workshop.png",
    rulebook: "../rulebook/COMP/decrypt.pdf",
    image: "https://raw.githubusercontent.com/TECHYON2022/techyonAssets/main/ETC/thumbnail/VFX.png",
  },
  {
    id: 48,
    eventName: "PCB Design",
    department: "ECOMP Department",
    categories: ["ETC"],
    type: "Intra",
    team: false,
    location: "Offline (EComp Floor Lab 6)",
    date: "27th OCT",
    time: "11 AM",
    event_coordinators: [
      {
        name: "Aman Bhandare",
        phone: "9359244086",
      },
      {
        name: "Shama Ghatwal",
        phone: "9881885981",
      },
    ],
    rules: {
      Details: [
        "Open for all Classes (Free Participation)",
        "Get Hands-On experience of Designing a Printed Circuit Board (PCB) from a Professional Instructor.",
    "PCs with the required software (Eagel) will be provided to all the attendees.",
    "No prior knowledge about the Topic required.",
    "Registration through Google Form.",
    "Limited Seats available.",
    "Last Date of Registration: 26th Oct",
    "E-Certificate will be given at the end of the Session.",
    "By the End of This Workshop you’ll 1. know the basics of PCB 2. Future Scope in the Field 3. To Design PCB on Eagle",
      ],
    },
    prize: [],
    form: "https://forms.gle/gYkkVwxf4RVniHpFA",
    poster: "https://raw.githubusercontent.com/TECHYON2022/techyonAssets/main/ETC/posters/PCB Design Workshop.png",
    rulebook: "../rulebook/COMP/decrypt.pdf",
    image: "https://raw.githubusercontent.com/TECHYON2022/techyonAssets/main/ETC/thumbnail/PCB.png",
  },
];