export const nationalEvents = [
  {
      id: 51,
      eventName: "HackTech",
      department: "National Event",
      categories: ["NATIONAL"],
      type: "Inter",
      team: true,
      location: "Online",
      date: "25th OCT",
      time: "9 AM",
      event_coordinators: [
        {
          name: "Kanchan Patil",
          phone: "918208069554",
        },
        {
          name: "Vailanka Dias",
          phone: "919371834101",
        },
      ],
      rules: {
        "Registration": [
          "Team leaders will register on Unstop and fill the details of all team member. Registrations close at same time as round 1 submission closing time.",
          "Participants must be enrolled to Engineering degree programs."],
        "Round 1 rules": [
          "1.	Problem statements will be posted on 25th October 2022, 9:00 am. Submissions close on 27th October 2022, 10:00 am.",
          "2.	Maximum 3(THREE) members per team.",
          "3.	Teams can have members from different college/university.",
          "4.	Following components have to be submitted (fields will be provided to type answers):",
          "  a.	Problem Statement chosen",
          "  b.	Abstract of solution",
          "  c.	How will the solution help in real world?",
          "  d.	Public link (youtube/gdrive) to a video showcasing and explaining the working of the prototype.",
          "5.	Developed solutions should be original and not copied.",
          "6.	Use of existing templates is prohibited, however APIs if required can be used.",
        ],
        "Round 2": [
          "1.	10 teams will qualify for round 2.",
          "2.	Round 2 will be online discussion round conducted on 29th October 2022.",
          "3.	Selected teams have to join an online session with judges.",
          "4.	Team leader will be sent the meeting details via email on 28th October 2022. It is compulsory for all team members to join the session.",
          "5.	Teams are required to prepare necessary visual aids (presentation, etc.) in advance to present their solution. Teams are allowed to improve on their solution and fine tune it if needed.",
          "6.	The implementation of the solution will be discussed in detail and will be cross-questioned by judges.",
        ],
        "Evaluation Criteria": [
            "Originality of the idea",
            "Design considerations",
            "Implementation",
            "Use case relevance",
            "Performance of prototype",
        
            "Impact and Market Viability ",
            "Prototype Functionality",
            "Future Scope",
            "Q&A by judges",
            "Presentation skills ",
        ],
      },
     prize: [15000, 10000, 5000],
      form: "https://unstop.com/hackathon/hacktech-powered-by-visteon-techyon-2022-padre-conceicao-college-of-engineering-salcete-goa-462143",
      poster: "/assets/images/posters/comp/decrypt.jpg",
      rulebook: "../rulebook/COMP/decrypt.pdf",
      image: "https://raw.githubusercontent.com/TECHYON2022/techyonAssets/main/COMP/thumbnail/HackTech.png",
    },
]